CREATE TABLE IF NOT EXISTS CLEANING.VENTASDIARIAS
	(FECHA DATE
	,VENDED INT
	,PRODUCTO BIGINT
	,REFERENCIA TEXT
	,DESCRIPCION  TEXT
	,CANTIDAD FLOAT
	,VALOR  FLOAT
	,HashKey_BK TEXT
	,Hashkey_Data TEXT
	,DATA_Source TEXT
	,ModifiedDate TIMESTAMP);
	