CREATE TABLE IF NOT EXISTS core.FAC_VentasDiarias
	(VED_FECHA DATE
	,VED_VENDED INT
	,VED_PRODUCTO BIGINT
	,VED_REFERENCIA TEXT
	,VED_DESCRIPCION  TEXT
	,VED_CANTIDAD FLOAT
	,VED_VALOR  FLOAT
	,VED_HashKey_BK TEXT
	,VED_Hashkey_Data TEXT
	,VED_Valid_From TIMESTAMP
	,VED_Valid_To TIMESTAMP
	,VED_Current_Flag varchar(5)
	,VED_DML_Strat varchar(30)
	,VED_DATA_Source TEXT
	,VED_ModifiedDate TIMESTAMP);

