CREATE TABLE IF NOT EXISTS CLEANING.PRODUCTO
	(LINEA_NOMBRE TEXT 
	,LINEA INT
	,LINEA_DESCRIPCION TEXT 
	,GRUPO_NOMBRE TEXT
	,GRUPO INT
	,GRUPO_DESCRIPCION TEXT
	,PRODUCTO BIGINT
	,MARCA TEXT 
	,HashKey_BK TEXT
	,Hashkey_Data TEXT
	,DATA_Source TEXT
	,ModifiedDate TIMESTAMP);