INSERT INTO CLEANING.PRODUCTO
	(LINEA_NOMBRE 
	,LINEA 
	,LINEA_DESCRIPCION 
	,GRUPO_NOMBRE 
	,GRUPO 
	,GRUPO_DESCRIPCION 
	,PRODUCTO 
	,MARCA 
	,HashKey_BK
	,Hashkey_Data
	,DATA_Source 
	,ModifiedDate)
SELECT DISTINCT
	LINEA_NOMBRE 
	,LINEA 
	,LINEA_DESCRIPCION 
	,GRUPO_NOMBRE 
	,GRUPO 
	,GRUPO_DESCRIPCION 
	,PRODUCTO 
	,MARCA
	,md5(PRODUCTO::text)
	,md5(concat_ws('__',LINEA_NOMBRE,LINEA,LINEA_DESCRIPCION,GRUPO_NOMBRE,GRUPO,GRUPO_DESCRIPCION,MARCA))
	,'STAGE.VENTASDIARIAS'
	,NOW()
FROM STAGE.VentasDiarias
ORDER BY LINEA_DESCRIPCION;
