INSERT INTO CLEANING.VENTASDIARIAS
	(FECHA
	,VENDED
	,PRODUCTO
	,REFERENCIA
	,DESCRIPCION
	,CANTIDAD
	,VALOR
	,HashKey_BK
	,Hashkey_Data
	,DATA_Source 
	,ModifiedDate)
SELECT DISTINCT
	FECHA
	,VENDED
	,PRODUCTO
	,REFERENCIA
	,DESCRIPCION
	,CANTIDAD
	,VALOR
	,md5(concat_ws('__',VENDED,PRODUCTO,REFERENCIA,DESCRIPCION, EXTRACT(year from FECHA), EXTRACT(month from FECHA)))
	,md5(concat_ws('__',CANTIDAD,VALOR, VENDED,PRODUCTO,REFERENCIA,DESCRIPCION, EXTRACT(year from FECHA), EXTRACT(month from FECHA)))
	,'STAGE.VENTASDIARIAS'
	,NOW()
FROM STAGE.VentasDiarias
ORDER BY FECHA;
