SELECT DISTINCT
--	FECHA 
--	,ZONA 
--	,VENDED 
--	,CIUDAD 
--	,NOMBRE 
	LINEA_NOMBRE 
	,LINEA 
	,LINEA_DESCRIPCION 
	,GRUPO_NOMBRE 
	,GRUPO 
	,GRUPO_DESCRIPCION 
	,PRODUCTO 
--	,REFERENCIA 
--	,DESCRIPCION 
	,MARCA 
--	,CANTIDAD 
--	,VALOR 
--	,DATA_SOURCE 
--	,ModifiedDate 
--	,rowguid
FROM STAGE.VentasDiarias
ORDER BY LINEA_DESCRIPCION;
